In [1]:
import pandas as pd
import numpy as np
from PIL import Image


In [2]:
train_df = pd.read_csv('./train.csv')

In [3]:
train_df.head()

img_path  printer_id    print_id  \
0  101/1678589738/1678589914.060332.jpg         101  1678589738   
1  101/1678589738/1678589914.462857.jpg         101  1678589738   
2  101/1678589738/1678589914.875075.jpg         101  1678589738   
3  101/1678589738/1678589915.284495.jpg         101  1678589738   
4  101/1678589738/1678589915.700486.jpg         101  1678589738   

   has_under_extrusion  
0                    1  
1                    1  
2                    1  
3                    1  
4                    1

In [6]:
for pid in train_df.printer_id.unique():
    subset_df = train_df[train_df.printer_id == pid]
    # print(pid, len(subset_df.print_id.unique()),subset_df.print_id.unique())
    high_level_view = subset_df[['printer_id', 'print_id', 'has_under_extrusion']].drop_duplicates()
    print(pid, len(high_level_view), high_level_view)


101 9        printer_id    print_id  has_under_extrusion
0             101  1678589738                    1
2775          101  1678580155                    1
4347          101  1678591103                    1
5680          101  1678593348                    1
6705          101  1678594405                    1
9785          101  1678333984                    0
11481         101  1678337873                    0
14418         101  1678341667                    0
16834         101  1678344738                    0
102 6        printer_id    print_id  has_under_extrusion
20205         102  1678819096                    1
22901         102  1678816535                    1
27211         102  1678766920                    1
31035         102  1678761262                    1
35120         102  1678739903                    0
38729         102  1678736713                    0
103 8        printer_id    print_id  has_under_extrusion
42875         103  1679007451                    1
43997        

In [11]:
train_df.printer_id.value_counts()

102    22670
104    20766
101    20205
103     9927
22      7492
Name: printer_id, dtype: int64

In [54]:
for pid in train_df.printer_id.unique():
    subset_df = train_df[train_df.printer_id == pid]
    print(pid, len(subset_df.print_id.unique()),subset_df.print_id.unique())


101 9 [1678589738 1678580155 1678591103 1678593348 1678594405 1678333984
 1678337873 1678341667 1678344738]
102 6 [1678819096 1678816535 1678766920 1678761262 1678739903 1678736713]
103 8 [1679007451 1679008414 1679009928 1679011935 1678832038 1678834100
 1678834870 1678835470]
104 12 [1678450861 1678453862 1678454755 1679267208 1679270824 1678413653
 1678414274 1678415191 1678419624 1678445757 1679265796 1679221334]
22 17 [1672709609 1672767789 1672782493 1672773342 1672774625 1672775511
 1672777638 1672779510 1672780647 1672781765 1672793440 1672794032
 1672794804 1672792990 1672858778 1672868532 1672857603]


In [38]:
train_df.print_id.unique(), train_df.printer_id.unique()

(array([1678589738, 1678580155, 1678591103, 1678593348, 1678594405,
        1678333984, 1678337873, 1678341667, 1678344738, 1678819096,
        1678816535, 1678766920, 1678761262, 1678739903, 1678736713,
        1679007451, 1679008414, 1679009928, 1679011935, 1678832038,
        1678834100, 1678834870, 1678835470, 1678450861, 1678453862,
        1678454755, 1679267208, 1679270824, 1678413653, 1678414274,
        1678415191, 1678419624, 1678445757, 1679265796, 1679221334,
        1672709609, 1672767789, 1672782493, 1672773342, 1672774625,
        1672775511, 1672777638, 1672779510, 1672780647, 1672781765,
        1672793440, 1672794032, 1672794804, 1672792990, 1672858778,
        1672868532, 1672857603]),
 array([101, 102, 103, 104,  22]))

In [26]:
train_df[train_df['printer_id'].isin([22,103])].printer_id.unique()

array([103,  22])

In [7]:
PRINT_IDS_FOR_VAL_ONLY = [1672777638, 1672773342,1672767789, 1679265796, 1678415191]
PRINTERS_FOR_VAL_ONLY = [102]

(train_df[(train_df['printer_id'].isin(PRINTERS_FOR_VAL_ONLY) |
          train_df['print_id'].isin(PRINT_IDS_FOR_VAL_ONLY)
          )].printer_id.unique() , 
          
train_df[train_df['printer_id'].isin(PRINTERS_FOR_VAL_ONLY)
          ].printer_id.unique() ,

train_df[
          train_df['print_id'].isin(PRINT_IDS_FOR_VAL_ONLY)
          ].printer_id.unique())

(array([102, 104,  22]), array([102]), array([104,  22]))

In [8]:
from transformers import AutoModelForImageClassification

In [10]:
model = AutoModelForImageClassification.from_pretrained('google/bit-50')

KeyError: 'bit'

In [23]:
model

ViTForImageClassification(
  (vit): ViTModel(
    (embeddings): ViTEmbeddings(
      (patch_embeddings): ViTPatchEmbeddings(
        (projection): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
      )
      (dropout): Dropout(p=0.3, inplace=False)
    )
    (encoder): ViTEncoder(
      (layer): ModuleList(
        (0): ViTLayer(
          (attention): ViTAttention(
            (attention): ViTSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.0, inplace=False)
            )
            (output): ViTSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.3, inplace=False)
            )
          )
          (intermediate): ViTIntermediate(
            (dense): Linear(in_features=768, out_

In [44]:
test_df = pd.read_csv('./test.csv')

In [45]:
test_df.printer_id.value_counts()

21     8150
104    4921
102    4355
23     3397
101    1927
103    1275
22     1254
Name: printer_id, dtype: int64

In [12]:
from caxton_model import network_module

caxton_model = network_module.ParametersClassifier(2)

In [13]:
caxton_model

ParametersClassifier(
  (attention_model): ResidualAttentionModel_56(
    (conv1): Sequential(
      (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
      (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
    )
    (mpool1): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (residual_block1): ResidualBlock(
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn3): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
   