In [10]:
import pandas as pd
import numpy as np
from PIL import Image


In [2]:
train_df = pd.read_csv('./train.csv')

In [3]:
train_df.head()

img_path  printer_id    print_id  \
0  101/1678589738/1678589914.060332.jpg         101  1678589738   
1  101/1678589738/1678589914.462857.jpg         101  1678589738   
2  101/1678589738/1678589914.875075.jpg         101  1678589738   
3  101/1678589738/1678589915.284495.jpg         101  1678589738   
4  101/1678589738/1678589915.700486.jpg         101  1678589738   

   has_under_extrusion  
0                    1  
1                    1  
2                    1  
3                    1  
4                    1

In [8]:
np.unique(train_df.printer_id.values, return_counts=True)

(array([ 22, 101, 102, 103, 104]), array([ 7492, 20205, 22670,  9927, 20766]))

In [9]:
prints_22 = train_df[train_df.printer_id in '22']
prints_103 = train_df[train_df.printer_id == '103']

In [38]:
train_df.print_id.unique(), train_df.printer_id.unique()

(array([1678589738, 1678580155, 1678591103, 1678593348, 1678594405,
        1678333984, 1678337873, 1678341667, 1678344738, 1678819096,
        1678816535, 1678766920, 1678761262, 1678739903, 1678736713,
        1679007451, 1679008414, 1679009928, 1679011935, 1678832038,
        1678834100, 1678834870, 1678835470, 1678450861, 1678453862,
        1678454755, 1679267208, 1679270824, 1678413653, 1678414274,
        1678415191, 1678419624, 1678445757, 1679265796, 1679221334,
        1672709609, 1672767789, 1672782493, 1672773342, 1672774625,
        1672775511, 1672777638, 1672779510, 1672780647, 1672781765,
        1672793440, 1672794032, 1672794804, 1672792990, 1672858778,
        1672868532, 1672857603]),
 array([101, 102, 103, 104,  22]))

In [26]:
train_df[train_df['printer_id'].isin([22,103])].printer_id.unique()

array([103,  22])

In [43]:
PRINT_IDS_FOR_VAL = [1678589738, 1672794032, 1678413653, 1672774625]


(train_df[~(train_df['printer_id'].isin([103]) |
          train_df['print_id'].isin(PRINT_IDS_FOR_VAL)
          )].printer_id.unique() , 
          
train_df[train_df['printer_id'].isin([103])
          ].printer_id.unique() ,

train_df[
          train_df['print_id'].isin(PRINT_IDS_FOR_VAL)
          ].printer_id.unique())

(array([101, 102, 104,  22]), array([103]), array([101, 104,  22]))

In [18]:
from transformers import AutoModelForImageClassification

In [22]:
model = AutoModelForImageClassification.from_pretrained('google/vit-base-patch16-224', hidden_dropout_prob=0.3)

Downloading:   0%|          | 0.00/69.7k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/346M [00:00<?, ?B/s]

In [23]:
model

ViTForImageClassification(
  (vit): ViTModel(
    (embeddings): ViTEmbeddings(
      (patch_embeddings): ViTPatchEmbeddings(
        (projection): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
      )
      (dropout): Dropout(p=0.3, inplace=False)
    )
    (encoder): ViTEncoder(
      (layer): ModuleList(
        (0): ViTLayer(
          (attention): ViTAttention(
            (attention): ViTSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.0, inplace=False)
            )
            (output): ViTSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.3, inplace=False)
            )
          )
          (intermediate): ViTIntermediate(
            (dense): Linear(in_features=768, out_